# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showinfo',
            name='headimge',
            field=models.ImageField(default='normal.png', upload_to='static/images/headimage', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='showinfo',
            name='nickname',
            field=models.CharField(default='我本无名', max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='showinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo'),
        ),
    ]
