# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20180920_1152'),
        ('operate', '0002_auto_20180919_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcontent', models.CharField(max_length=300, verbose_name='回复内容')),
                ('rtime', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
                ('rcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operate.Comment')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
                'db_table': 'reply',
            },
        ),
    ]
